permalink: /:categories/:title.html
url: "http://krislee.github.io/blog/"
full_name: "Jingli Lee"
first_name: "Jingli"
last_name: "Lee"
blog_title: "Hello Blog"
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "Jingli"
copyright_year: "2015"
google_analytics_code: ""
aboutme: "Something about the author here"
twitter: "Jingli"
github: "krislee"
linkined_url: ""
